### ISSUE TITLE
Various minor issues with 2.0-rc1

### ISSUE THREAD

**Issue by agarny** [cellml/cellml-specification#197]
I have several minor issues that I didn't think deserved an issue of their own:
- General:
  - [x] #214 Check all the links (a lot of them are broken). 
  - [x] Is there any rationale for our use of italics? Yes, see https://github.com/cellml/cellml-specification/issues/197#issuecomment-614380841
  - [x] #218 Sometimes "CellML namespace" is a link, sometimes it is not. The first occurrence of "CellML namespace" in a section should be a link. 
  - [x] #220 Be consistent in our use of numbered lists, i.e. use ";" at the end of an item rather than ".", except for the last item. May also decide on whether to use a final "and"/"or" (e.g., see 1.2.2.1 vs. 1.2.5.1 vs. 1.3.1 vs. 2.1.2). 
- Contents:
  - [ ] #221 Move 2.12 (`math` element) to 2.9, i.e. before `reset` element? It's just that we can perfectly have a model without resets, so the `reset` & Co. elements should be considered as "add-ons" and I would thefeore expect them to come after the `math` element. 
- Preample:
  - [x]  #227 "A PDF [version] of this [document] is available [at]..."
  - [x] (discussion below) ~Add a full stop at the end of "Contact: editors@cellml.org".~
- 1.1 Terminology:
  - [x] #222 No need to mention the "REQUIRED", "SHOULD", "SHOULD NOT", "RECOMMENDED" and "OPTIONAL" keywords. They are never used in the spec. 
  - [x] #222 CellML infoset: "In this specification[,] such infosets are assumed to be CellML 2.0 infosets." (missing comma)
  - [x] ~CellML model: Use "top-most" or then "toplevel". We use "top-level" somewhere else, so probably "top-most" then.~
  - [x] #222 Whitespace character: list the Unicode characters in order, i.e. U+0009, U+000A, U+000D or U+0020.
- 1.2 CellML information sets:
  - [x] (discussion below) 1.2.3.1: replace "... making any or none of..." with "... making none or any of..."?
  - [x] #223 Does 1.2.4.1 make sense (Character information items)?
  - [x] #220 1.2.5.1: add ";" at the end of the first namespace  and "." at the end of the second namespace.
  - [x] #201 1.2.5.1: are we supporting other namespaces besides the CellML and MathML ones? A quick search tells me that we don't, so no need for ", unless explicitly indicated otherwise".
  - [x] ~because of 1.3.1.2, 1.3.1.1 is not needed. It doesn't harm though.~ number format text has changed since
- 2.1 The `model` element:
  - [x] #225 (and discussion below) 2.1.2: I would reorder the list: `import`, `units`, `component`, `encapsulation` and then `connection`. That order is more logical to me.
- 2.3 The `import units` element:
  - [x] (discussion below) 2.3.2: do we really want to say that "The value of the `units_ref` attribute MUST match the value of the `name` attribute on a `units` or `import units` element in the imported CellML infoset."? I mean, there is no way we can ensure that during validation, or is there...? (The same for 2.4.2.)
- 2.5 The `units` element:
  - [x]  #224 (and discussion below) Why do we mention that a `units` element must have a `model` element as its parent? For one, there is only one `model` element, so it should be "the `model` element"? Also, we don't mention this for the `import` element (see 2.2), but do for the `component`, `encapsulation` and `connection` elements, although we phrase it slightly differently. Still, 2.1.2 mentions the type of child elements a `model` element can have, so we shouldn't need to repeat ourselves.
- 2.6 The `unit` element:
  - [x] #232 (discussion below) 2.6.1.2: delete "(in other words, units definitions must not be cyclical)". If this is really what we want to say then we should say it in the first place. See https://github.com/cellml/cellml-specification/issues/197#issuecomment-614368526
- 2.7 The `component` element:
  - [x] #225 ~2.7.2: for logical reasons, I would have `variable`, `math` and then `reset` elements.~ See https://github.com/cellml/cellml-specification/issues/197#issuecomment-614370317
- 2.9 The `reset` element:
  - [x] #233 (discussion below) 2.9.1: "... exactly one [of] each of..." 
- 2.12 #234 The `math` element:
  - [x] Merge 2.12.5 and 2.12.6? I.e. have something like "A `cn` element MUST be one of the following types: real or e-notation, and MUST be of base 10.".
  - [x] Table 2.1: why is there some space before and after the element list for "Arithmetic Operators" and "Trigonometric Operators"? It's clearly not a big issue, but it looks odd.
  - [x] Footnote for Table 2.1: "must" should be replaced with "MUST"?
- 2.14 The `component_ref` element (see discussion https://github.com/cellml/cellml-specification/issues/197#issuecomment-614376550 ):
  - [x] #235 2.14.2 reads "... MAY in turn contain one or more `component_ref` element children" while in 2.13.1 it reads "... MAY contains one or more `component_ref` elements." So, we are not being consistent. Personally, I would, from 2.14.2, remove "in turn" and replace "element children" with "elements". The same may have to be done elsewhere, I haven't checked.
- [x] #236 Chapter 3 everywhere: we've had some "element information items" creep back in from somewhere ... need to remove in favour of our defined "elements" terminology.

**Comment by kerimoyle** [comment]
> CellML infoset: "In this specification[,] such infosets are assumed to be CellML 2.0 infosets." (missing comma) 

(... I cringe when I see commas used like this ... )

>  2.1.3: why "... MUST NOT contain more than one..."? Why not simply "... MUST contain only one ..."?

Because it can contain none?

> Whitespace character: list the Unicode characters in order, i.e. U+0009, U+000A, U+000D or U+0020.

I think they're currently in order of use: space, tab, line feed, new line, etc?

Re links everywhere, these currently have to be manually added.  I've deliberately not added them to every single reference on every single page as this just makes the code super cluttered, and it's not great for the reader either.  I've tried to add them as you would when defining a new acronym or term - once at the beginning of the section, so that people reading that part will encounter it and can click if they need to.  I've probably missed a lot ... but that's why it's not strictly the same everywhere...

**Comment by kerimoyle** [comment]
Can we add the issue #194 to your list too please?

**Comment by agarny** [comment]
> > CellML infoset: "In this specification[,] such infosets are assumed to be CellML 2.0 infosets." (missing comma)
> (... I cringe when I see commas used like this ... )

Why?

> > 2.1.3: why "... MUST NOT contain more than one..."? Why not simply "... MUST contain only one ..."?
> 
> Because it can contain none?

Doh, of course! Thanks, I am going to remove that from my list.

> > Whitespace character: list the Unicode characters in order, i.e. U+0009, U+000A, U+000D or U+0020.
> 
> I think they're currently in order of use: space, tab, line feed, new line, etc?

Sure, it's just that people don't necessarily know that U+0020 is space, etc. So, I would just oder them by numerical value.

> Re links everywhere, these currently have to be manually added. I've deliberately not added them to every single reference on every single page as this just makes the code super cluttered, and it's not great for the reader either. I've tried to add them as you would when defining a new acronym or term - once at the beginning of the section, so that people reading that part will encounter it and can click if they need to. I've probably missed a lot ... but that's why it's not strictly the same everywhere...

I am fine with your intention, but otherwise, yes, some have been missed. So, ok, I am going to leave that bullet point and update my comment accordingly.

> Can we add the issue #194 to your list too please?

Ok, consider it done.

**Comment by kerimoyle** [comment]
> Why?

It's not necessary (I don't think it's even correct?) and it gets in the way of reading.

**Comment by agarny** [comment]
> > Why?
> It's not necessary (I don't think it's even correct?) and it gets in the way of reading.

Interesting, for me, I need it or I find it confusing (and I think it might grammatically be needed, but don't quote me on that).

**Comment by MichaelClerx** [comment]
>  Is there any rationale for our use of italics?

I'm struggling to find an example!

**Comment by MichaelClerx** [comment]
> Add a full stop at the end of "Contact: editors@cellml.org". 

That will just make it harder for people to copy paste the email address

**Comment by MichaelClerx** [comment]
> CellML model: Use "top-most" or then "toplevel". We use "top-level" somewhere else, so probably "top-most" then.

Topmost is a word https://www.google.com/search?q=topmost&oq=topmost&aqs=chrome..69i57.700j0j7&sourceid=chrome&ie=UTF-8 so doesn't take a hyphen

**Comment by MichaelClerx** [comment]
> 1.2.3.1: replace "... making any or none of..." with "... making none or any of..."?

any or none sounds better, and "any" is the main bit ("or none" is a pedantic afterthought)

**Comment by MichaelClerx** [comment]
> 2.1.2: I would reorder the list: import, units, component, encapsulation and then connection. That order is more logical to me.

I would always put imports last, because they depend on units and components.

However, this just shows that the logical order is subjective, so we should stick with the alphabetical order I think

**Comment by MichaelClerx** [comment]
> 2.3.2: do we really want to say that "The value of the `units_ref` attribute MUST match the value of the `name` attribute on a `units` or `import units` element in the imported CellML infoset."? I mean, there is no way we can ensure that during validation, or is there...? (The same for 2.4.2.)

Absolutely!

This is one of many rules you can only check by parsing the full model (in this case including imports). So yes it will create difficulties for e.g. schema validation, but so will e.g. unit mismatches between connected components.

**Comment by MichaelClerx** [comment]
>  Why do we mention that a units element must have a model element as its parent? For one, there is only one model element, so it should be "the model element"? Also, we don't mention this for the import element (see 2.2), but do for the component, encapsulation and connection elements, although we phrase it slightly differently. Still, 2.1.2 mentions the type of child elements a model element can have, so we shouldn't need to repeat ourselves.

We have 

> A `unit` element information item (referred to in this specification as a `unit` element) is an element in the CellML namespace with a local name equal to `unit`, and with a `units` element as its parent.

and 

> An `import units` element information item (referred to in this specification as an `import units` element) is an element in the CellML namespace with a local name equal to `units`, which appears as a child of an `import` element.

So both have local name `unit`, but can only be distinguished by where they appear. 

Similarly

> A `component` element information item (referred to in this specification as a `component` element) is an element in the CellML namespace with a local name equal to `component`, and which appears as a child of a `model` element.

and

> An `import component` element information item (referred to in this specification as an `import component` element) is an element in the CellML namespace with a local name equal to `component`, which appears as a child of an `import` element.

Why we say it for the `encapsulation` element I don't know.

**Comment by MichaelClerx** [comment]
> For one, there is only one model element, so it should be "the model element"?

In chapter 2, we consistently talk about "a" model element, in general. Same for "an encapsulation element" for which there is one per model, but lots in the world.

**Comment by MichaelClerx** [comment]
> Why we say it for the encapsulation element I don't know.

We do this for other elements too, and personally I find it helpful! It's redundant though, yes!

**Comment by MichaelClerx** [comment]
> 2.6.1.2: delete "(in other words, units definitions must not be cyclical)". If this is really what we want to say then we should say it in the first place.

We really want to say so. That's the only purpose of 2.6.1.1 and 2.6.1.2

But it's maybe not that obvious that this is what those paragraphs imply, so I think it's a really good idea to state it again, at the end

**Comment by MichaelClerx** [comment]
> 2.9.1: "... exactly one [of] each of..."

I prefer just "one each of", but this https://ell.stackexchange.com/questions/54062/one-each-is-this-grammatically-an-okay-phrase seems to suggest that this is unclear to non-native speakers?

**Comment by MichaelClerx** [comment]
I've addressed each of these points now, except for the italics @agarny !

**Comment by agarny** [comment]
> > Add a full stop at the end of "Contact: [editors@cellml.org](mailto:editors@cellml.org)".
> That will just make it harder for people to copy paste the email address

It's a link, so it shouldn't be a problem. Either people click on the link or right click on it to copy it.

**Comment by kerimoyle** [comment]
I agree, I don't think it should have a fullstop.

**Comment by kerimoyle** [comment]
> 1.2.3.1: replace "... making any or none of..." with "... making none or any of..."?

> any or none sounds better, and "any" is the main bit ("or none" is a pedantic afterthought)

I think "any or none" is better.

**Comment by agarny** [comment]
FWIW, last time, I was done with 2.9. So, I have added a few more from 2.10 (well, 2.12 since I am fine with 2.10 and 2.11).

**Comment by kerimoyle** [comment]
> The value of the units attribute MUST NOT be such that the units element inclusion digraph contains one or more cycles (in other words, units definitions must not be cyclical).

Re 2.6: Replace with:
"The units element inclusion digraph MUST NOT contain one or more cycles."
We've already defined what things make up the digraph, we don't need to re-tell how it's constructed, only that it can't be cyclical.

**Comment by kerimoyle** [comment]
2.7: We have alphabetical order everywhere else, better to be consistent.

**Comment by agarny** [comment]
> 2.7: We have alphabetical order everywhere else, better to be consistent.

I like consistency, so ok.

**Comment by kerimoyle** [comment]
> 2.14 The component_ref element:
 2.14.2 reads "... MAY in turn contain one or more component_ref element children" while in 2.13.1 it reads "... MAY contains one or more component_ref elements." So, we are not being consistent. Personally, I would, from 2.14.2, remove "in turn" and replace "element children" with "elements". The same may have to be done elsewhere, I haven't checked.

Going through the sections we use "element children" in:
- models, imports, units, components, resets, component_refs, 

We don't use it in:
- encapsulations, connections

I'm going to go with the majority and add it to encapsulations and connections ... :)

**Comment by kerimoyle** [comment]
> 2.3.2: do we really want to say that "The value of the units_ref attribute MUST match the value of the name attribute on a units or import units element in the imported CellML infoset."? I mean, there is no way we can ensure that during validation, or is there...? (The same for 2.4.2.)

Why can't we include it in validation?  It just means that we now have resolve imported files ... which then means that the *model* is validated, rather than just the *document* containing the first `model` tag ... which is better, isn't it?

See also https://github.com/cellml/cellml-specification/issues/197#issuecomment-614018003

**Comment by kerimoyle** [comment]
> Is there any rationale for our use of italics?

It seems that we *have* used italics consistently for things like "variable _A_" or "component _BB_".  We may need to include some others too, but what's there at the moment are only of these type.

**Comment by agarny** [comment]
> > Is there any rationale for our use of italics?
> 
> It seems that we _have_ used italics consistently for things like "variable _A_" or "component _BB_". We may need to include some others too, but what's there at the moment are only of these type.
> 
> I've checked, and we don't seem to be missing this kind of thing from anywhere else. Was there something which prompted this question @agarny ?

Yes, in section "1.1 Terminology" for example, I don't understand why "CellML namespace", "Basic Latin alphabetic character" and "European numeral" are in italics, but maybe it's just me...?

**Comment by agarny** [comment]
> > 2.3.2: do we really want to say that "The value of the units_ref attribute MUST match the value of the name attribute on a units or import units element in the imported CellML infoset."? I mean, there is no way we can ensure that during validation, or is there...? (The same for 2.4.2.)
> 
> Why can't we include it in validation? It just means that we now have resolve imported files ... which then means that the _model_ is validated, rather than just the _document_ containing the first `model` tag ... which is better, isn't it?

Ideally, I would like to see that, but I understand that when it comes to validation we only want to validate the current document. One possible reason is that an imported CellML file may be a remote file and we don't want libCellML to retrieve a file located somewhere on the internet. @nickerso and @hsorby might be able to provide other/better reasons.

**Comment by kerimoyle** [comment]
Weird, mine are bold?  I used bold here so that they would stand out from the rest of the text, like a glossary or dictionary.  If that's against the rules then I can remove it I guess ... ?
 
![image](https://user-images.githubusercontent.com/46887220/79415368-5655af00-8001-11ea-9d39-ab2f58384322.png)

**Comment by kerimoyle** [comment]
Or are you talking about the formatting of the hover links?? Again, mine aren't italics either:
![image](https://user-images.githubusercontent.com/46887220/79415590-e136a980-8001-11ea-8e6b-9b996e55c42c.png)

**Comment by kerimoyle** [comment]
Ahhhh ... you mean in the PDF? That's the formatting that Latex adds for hyperlinks.

**Comment by agarny** [comment]
Yes, I meant the PDF since that's what we had to review. :) Anyway, why isn't "RFC 2119" in italics then?

**Comment by kerimoyle** [comment]
It's for internal hyperlinks only, external ones have a slightly different colour but no italics.

**Comment by agarny** [comment]
Hmm, ok, it kind of makes sense once you know about it. I wonder whether we couldn't have a regular link and a symbol next to it to indicate that it's an external link? However, there is no Unicode character for that, just images (e.g. https://www.iconfinder.com/icons/3325117/external_link_icon).

**Comment by MichaelClerx** [comment]
Only remaining point is in its own ticket, so closing again :D
